{{- if .Values.services.init.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.services.init.name | default "mcp-init" }}-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.services.init.name | default "mcp-init" }}
    {{- include "mcpcan.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.services.init.name | default "mcp-init" }}
        {{- include "mcpcan.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.services.init.name | default "mcp-init" }}
        image: {{ if .Values.global.cn }}{{ .Values.global.registryForMirrorCN }}{{ else }}{{ .Values.global.registry }}{{ end }}/{{ .Values.services.init.name | default "mcp-init" }}:{{ .Values.global.version }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        {{- if .Values.services.init.resources }}
        resources:
          {{- toYaml .Values.services.init.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: "/app/config"
          readOnly: true
        - name: k8s-config-volume
          mountPath: {{ .Values.services.init.k8sHostPath.mountPath | default "/app/config/kube" }}
          readOnly: {{ .Values.services.init.k8sHostPath.readOnly | default true }}
        - name: data-volume
          mountPath: {{ .Values.global.mountStorage.rootPath | default "/data/mcpcan" }}
      volumes:
      - name: config-volume
        configMap:
          name: mcp-config
          items:
          - key: "init.yaml"
            path: "init.yaml"
      - name: k8s-config-volume
        hostPath:
          path: {{ .Values.services.init.k8sHostPath.path }}
          type: {{ .Values.services.init.k8sHostPath.type }}
      - name: data-volume
        hostPath:
          path: {{ .Values.global.hostStorage.rootPath | default "/data/mcpcan" }}
          type: DirectoryOrCreate
      restartPolicy: OnFailure
  backoffLimit: {{ .Values.services.init.backoffLimit | default 3 }}
{{- end }}