{{- if and .Values.ingress.tls.createSecret .Values.ingress.tls.enabled .Values.ingress.tls.crt .Values.ingress.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName | default (printf "%s-secret" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcpcan.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-90"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt | b64enc }}
  tls.key: {{ .Values.ingress.tls.key | b64enc }}
{{- end }}
