runMode: prod
server:
  httpPort: 8081
secret: MrKuvLNn0hc1kHRbA6EqjSPj1ecrbPDE
database:
  mysql:
    host: mysql
    port: 3306
    database: mcpcan
    username: mcpcan-user
    password: a6ApqYJIycJJjl
  redis:
    host: redis
    port: 6379
    password: dHaARm88OXXN6e
    db: 0
log:
  level: debug
  format: json
storage:
  rootPath: ./data/mcpcan
  codePath: ./data/mcpcan/code-package
  staticPath: ./data/mcpcan/static
