runMode: prod
server:
  httpPort: 8081
secret: MrKuvLNn0hc1kHRbA6EqjSPj1ecrbPDE
database:
  mysql:
    host: mysql
    port: 3306
    database: mcp_dev
    username: mcp_user
    password: dev-password
  redis:
    host: redis
    port: 6379
    password: dev-redis-password
    db: 0
log:
  level: debug
  format: json
storage:
  rootPath: ./data/mcpcan
  codePath: ./data/mcpcan/code-package
  staticPath: ./data/mcpcan/static
