server:
  httpPort: 8082
database:
  mysql:
    host: mysql
    port: 3306
    database: mcpcan
    username: mcpcan-user
    password: a6ApqYJIycJJjl
  redis:
    host: redis
    port: 6379
    password: dHaARm88OXXN6e
    db: 0
log:
  level: debug
  format: json
