runMode: prod
init:
  admin_username: admin
  admin_password: admin123
  admin_nickname: admin
  admin_role_name: admin
  admin_role_description: admin role
  admin_role_level: 1
  admin_data_scope: all
database:
  mysql:
    host: mysql
    port: 3306
    database: mcpcan
    username: mcpcan-user
    password: a6ApqYJIycJJjl
  redis:
    host: redis
    port: 6379
    password: dHaARm88OXXN6e
    db: 0
storage:
  rootPath: /data/mcpcan
  codePath: /data/mcpcan/code-package
  staticPath: /data/mcpcan/static
log:
  level: debug
  format: json
