runMode: prod
server:
  httpPort: 8080
secret: MrKuvLNn0hc1kHRbA6EqjSPj1ecrbPDE
runEnvironment:
  enabled: true
  name: "Default-Run-Environment"
  type: "docker"
  docker:
    host: "unix:///var/run/docker.sock"
    network: "docker-compose_mcpcan-network"
services:
  mcpMarket:
    host: mcp-market
    port: 8080
  mcpAuthz:
    host: mcp-authz
    port: 8081
database:
  mysql:
    host: mysql
    port: 3306
    database: mcpcan
    username: mcpcan-user
    password: a6ApqYJIycJJjl
  redis:
    host: redis
    port: 6379
    password: dHaARm88OXXN6e
log:
  level: debug
  format: json
code:
  upload:
    maxFileSize: 100
    allowedExtensions: .zip,.tar.gz,.tar,.dxt,.mcpb
storage:
  rootPath: /data/mcpcan
  codePath: /data/mcpcan/code-package
  staticPath: /data/mcpcan/static
  openapiFilePath: /data/mcpcan/openapi-file
