apiVersion: v2
name: mcpcan-deploy
description: A Helm chart for MCPCan - Microservices Container Platform
type: application
version: v1.10.2
appVersion: v1.10.2
keywords:
  - mcpcan
  - microservices
  - platform
  - kubernetes
home: https://github.com/Kymo-MCP/mcpcan
sources:
  - https://github.com/Kymo-MCP/mcpcan
maintainers:
  - name: MCPCan Team
    email: opensource@kymo.cn